### ISSUE TITLE
as for cuda=11.8,update env.yml 

### ISSUE THREAD

**Issue by AtticusZeller** [zju3dv/NeuralRecon#145]
```yaml
# cuda in system ==11.8
name: neucon
channels:
  - pytorch
  - defaults
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.0.0
  - torchvision=0.15.0 
  - torchaudio=2.0.0
  - pytorch-cuda=11.8
  - ipython
  - tqdm
  - numba
  - sparsehash  # dependency for torchsparse
  - pip
  - pip:
    - -r requirements.txt
    - git+https://github.com/mit-han-lab/torchsparse.git@v2.0.0
# torchsparse.git@v2.0.0 must be v2.0.0, the higher version has changed api!!!
# and it may take times to build wheels which is like compiling the source code.
```
it works for me running demo,
wsl,ubuntu22,RTX4060,cuda==11.8
